# Generated by Django 6.0.2 on 2026-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifestyle_services", "0003_remove_revenuecat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lifestylesubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending payment"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
