# Generated by Django 6.0.2 on 2026-04-13 12:12

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_services_to_sections(apps, schema_editor):
    """One section 'Included' with a benefit line per legacy LifestyleService row."""
    LifestylePlan = apps.get_model("lifestyle_services", "LifestylePlan")
    LifestyleService = apps.get_model("lifestyle_services", "LifestyleService")
    LifestylePlanSection = apps.get_model("lifestyle_services", "LifestylePlanSection")
    LifestylePlanBenefit = apps.get_model("lifestyle_services", "LifestylePlanBenefit")

    labels = {
        "cleaning": "Cleaning",
        "internet": "Internet",
        "maintenance": "Maintenance",
        "furniture": "Furniture",
        "gym": "Gym",
        "support": "Support",
    }

    for plan in LifestylePlan.objects.all():
        if LifestylePlanSection.objects.filter(plan=plan).exists():
            continue
        section = LifestylePlanSection.objects.create(
            plan=plan,
            title="Included",
            emoji="",
            sort_order=0,
        )
        for i, svc in enumerate(
            LifestyleService.objects.filter(plan=plan).order_by("service_type")
        ):
            label = labels.get(svc.service_type, svc.service_type)
            text = f"{label}: {svc.details}" if svc.details else label
            LifestylePlanBenefit.objects.create(
                section=section, text=text[:500], sort_order=i
            )


class Migration(migrations.Migration):

    dependencies = [
        ("lifestyle_services", "0004_subscription_checkout_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="lifestyleplan",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="If false, plan is hidden from the public lifestyle-plans API (existing subscriptions unchanged).",
            ),
        ),
        migrations.AddField(
            model_name="lifestyleplan",
            name="is_most_popular",
            field=models.BooleanField(
                default=False,
                help_text="Show “most popular” styling on the lifestyle page.",
            ),
        ),
        migrations.AddField(
            model_name="lifestyleplan",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Short audience line under the plan name (e.g. Young professionals & single expats).",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="LifestylePlanSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "emoji",
                    models.CharField(
                        blank=True,
                        help_text="Optional emoji or icon key shown before the section title.",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="lifestyle_services.lifestyleplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lifestyle plan section",
                "verbose_name_plural": "Lifestyle plan sections",
                "ordering": ["plan", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LifestylePlanBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="lifestyle_services.lifestyleplansection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lifestyle plan benefit",
                "verbose_name_plural": "Lifestyle plan benefits",
                "ordering": ["section", "sort_order", "id"],
            },
        ),
        migrations.RunPython(
            migrate_legacy_services_to_sections,
            migrations.RunPython.noop,
        ),
    ]
