# Generated by Django 6.0.2 on 2026-04-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifestyle_services", "0005_plan_sections_and_benefits"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifestylePartner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("gym", "Gym"),
                            ("cleaning_vendor", "Cleaning vendor"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "area_label",
                    models.CharField(
                        blank=True,
                        help_text="Neighborhood or area (e.g. Dubai Marina).",
                        max_length=120,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lifestyle partner",
                "verbose_name_plural": "Lifestyle partners",
                "ordering": ["partner_type", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LifestyleSubscriptionPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cleaning_weekday",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                        ],
                        default="wed",
                        max_length=3,
                    ),
                ),
                (
                    "cleaning_time_window",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (8am–12pm)"),
                            ("afternoon", "Afternoon (12pm–5pm)"),
                            ("evening", "Evening (5pm–9pm)"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Access instructions, pet notes, or other context for partners.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gym_partner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_active": True, "partner_type": "gym"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gym_subscriptions",
                        to="lifestyle_services.lifestylepartner",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifestyle_preferences",
                        to="lifestyle_services.lifestylesubscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lifestyle subscription preference",
                "verbose_name_plural": "Lifestyle subscription preferences",
            },
        ),
    ]
