# Generated by Django 6.0.2 on 2026-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="trakheesi_permit_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="10-digit Trakheesi Advertising Permit number (Dubai).",
                max_length=10,
            ),
        ),
    ]
