# Generated by Django 6.0.2 on 2026-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_trakheesi_and_realtor_orn"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="leased",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True when a lease is fully signed for this listing - hidden from public search; still visible to lister and renter with a reservation.",
            ),
        ),
    ]
