# Generated by Django 6.0.2 on 2026-04-02 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_postgresql_row_level_security"),
        ("documents", "0003_uae_verification_pipeline"),
        ("listings", "0003_listing_leased_flag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="title_deed_document",
            field=models.ForeignKey(
                blank=True,
                help_text="Ownership document for this unit; one listing per deed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings_by_title_deed",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="title_deed_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Plot / unit / property reference as shown on the title deed (must match the upload).",
                max_length=300,
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("title_deed_document__isnull", False)),
                fields=("title_deed_document",),
                name="unique_listing_per_title_deed_document",
            ),
        ),
    ]
