# Generated by Django 6.0.2 on 2026-04-10 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_listing_owner_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="assigned_realtor",
            field=models.ForeignKey(
                blank=True,
                help_text="Verified realtor chosen by the landlord when they list their own property.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="owner_verification_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason when rejected; optional comment when approved.",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="trakheesi_permit_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="10-digit Trakheesi Advertising Permit (Dubai), entered by the advertising broker.",
                max_length=10,
            ),
        ),
    ]
