# Generated by Django 6.0.2 on 2026-06-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_listingownerinvite"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="listingownerinvite",
            new_name="listings_li_listing_b7f53e_idx",
            old_name="listings_li_listing_6a0f8d_idx",
        ),
    ]
