# Generated by Django 6.0.2 on 2026-06-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_partnership_chat_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Smaller JPEG for cards and list views.",
                null=True,
                upload_to="listings/thumbs/",
            ),
        ),
    ]
