# Generated by Django 6.0.2 on 2026-03-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0002_reservation_notes_dld_fields"),
        ("payments", "0002_payment_team_message_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseSigningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending signatures"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "renter_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "lister_token",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("renter_signed_at", models.DateTimeField(blank=True, null=True)),
                ("lister_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Future: DocuSign envelope id, Dropbox Sign signature_request_id, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_signing",
                        to="bookings.reservation",
                    ),
                ),
                (
                    "triggering_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lease_signing_sessions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
