# Generated by Django 6.0.2 on 2026-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esign", "0001_esign_and_notification_esign"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasesigningsession",
            name="contract_pdf",
            field=models.FileField(
                blank=True,
                help_text="Generated lease PDF (baseline before signatures).",
                max_length=500,
                upload_to="esign/contracts/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="leasesigningsession",
            name="contract_pdf_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hex of contract_pdf at generation (integrity reference).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="leasesigningsession",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                help_text="Contract + signature certificate pages (updated as each party signs).",
                max_length=500,
                null=True,
                upload_to="esign/signed/%Y/%m/",
            ),
        ),
    ]
