# Generated by Django 6.0.2 on 2026-03-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esign", "0002_lease_pdf_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="leasesigningsession",
            name="lister_contract_pdf",
            field=models.FileField(
                blank=True,
                help_text="Tenancy contract uploaded by the listing owner / realtor; shown to both parties for signing.",
                max_length=500,
                upload_to="esign/lister_uploads/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="leasesigningsession",
            name="contract_pdf",
            field=models.FileField(
                blank=True,
                help_text="Auto-generated fallback PDF (dev) when no lister upload; superseded by lister_contract_pdf.",
                max_length=500,
                upload_to="esign/contracts/%Y/%m/",
            ),
        ),
    ]
