# Generated by Django 6.0.2 on 2026-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esign", "0006_signature_slots_per_placement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leasesigningsession",
            name="lister_signature_slot_1",
            field=models.FileField(
                blank=True,
                help_text="Lister PNG for placement 1 when contract uses three signature areas.",
                max_length=500,
                upload_to="esign/signatures/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="leasesigningsession",
            name="lister_signature_slot_2",
            field=models.FileField(
                blank=True,
                help_text="Lister PNG for placement 2.",
                max_length=500,
                upload_to="esign/signatures/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="leasesigningsession",
            name="lister_signature_slot_3",
            field=models.FileField(
                blank=True,
                help_text="Lister PNG for placement 3.",
                max_length=500,
                upload_to="esign/signatures/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="leasesigningsession",
            name="renter_signature_slot_1",
            field=models.FileField(
                blank=True,
                help_text="Renter PNG for placement 1 when contract uses three signature areas.",
                max_length=500,
                upload_to="esign/signatures/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="leasesigningsession",
            name="renter_signature_slot_2",
            field=models.FileField(
                blank=True,
                help_text="Renter PNG for placement 2.",
                max_length=500,
                upload_to="esign/signatures/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="leasesigningsession",
            name="renter_signature_slot_3",
            field=models.FileField(
                blank=True,
                help_text="Renter PNG for placement 3.",
                max_length=500,
                upload_to="esign/signatures/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="leasesigningsession",
            name="signed_pdf",
            field=models.FileField(
                blank=True,
                help_text="Signed contract: either overlays on signature_field_boxes or contract + certificate pages.",
                max_length=500,
                null=True,
                upload_to="esign/signed/%Y/%m/",
            ),
        ),
    ]
