# Generated by Django 6.0.2 on 2026-04-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("esign", "0008_lease_signing_audit_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="leasesigningauditevent",
            new_name="esign_lease_session_41910a_idx",
            old_name="esign_leases_session_0a8b2d_idx",
        ),
    ]
