# Generated by Django 6.0.2 on 2026-03-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="team_message_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Yallastay Team realtor notification was posted to the listing chat.",
                null=True,
            ),
        ),
    ]
