# Generated by Django 6.0.2 on 2026-04-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lifestyle_services", "0004_subscription_checkout_pipeline"),
        ("payments", "0002_payment_team_message_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="lifestyle_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription_payments",
                to="lifestyle_services.lifestylesubscription",
            ),
        ),
    ]
