"""Generate lease PDFs (ReportLab) and merge signature pages (pypdf) for dev/test.

Production should replace this path with DocuSign / Dropbox Sign (see docs/esign/pdf-signing-agreement.md).
"""

from __future__ import annotations

import hashlib
import io
import logging
from typing import TYPE_CHECKING

from django.core.files.base import ContentFile
from django.utils import timezone
from PIL import Image as PILImage
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from reportlab.platypus import Image as RLImage
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from pypdf import PdfReader, PdfWriter

from esign.parties import lease_signing_lister_user
from esign.signature_boxes import normalize_signature_field_boxes

if TYPE_CHECKING:
    from bookings.models import Reservation

    from esign.models import LeaseSigningSession

logger = logging.getLogger(__name__)


def sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _full_name(user) -> str:
    fn = (user.first_name or "").strip()
    ln = (user.last_name or "").strip()
    if fn or ln:
        return f"{fn} {ln}".strip()
    return user.email


def build_contract_pdf_bytes(reservation: Reservation) -> bytes:
    """Single-page (or multi) tenancy draft PDF for testing - not legal advice."""
    listing = reservation.listing
    renter = reservation.user
    lister = lease_signing_lister_user(listing)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        name="LeaseTitle",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=12,
    )
    body = ParagraphStyle(
        name="LeaseBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
    )
    story = []
    story.append(Paragraph("Tenancy agreement (draft - testing)", title_style))
    story.append(Spacer(1, 0.3 * cm))
    story.append(
        Paragraph(
            "This PDF is generated by Yallastay for <b>development and testing</b> only. "
            "Have UAE-qualified counsel review any production lease.",
            body,
        )
    )
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph(f"<b>Property:</b> {listing.title}", body))
    if listing.description:
        story.append(
            Paragraph(f"<b>Description:</b> {listing.description[:800]}", body)
        )
    story.append(
        Paragraph(
            f"<b>Rent (listing):</b> {listing.price} AED &nbsp; "
            f"<b>Reservation currency:</b> {reservation.currency}",
            body,
        )
    )
    story.append(
        Paragraph(
            f"<b>Term:</b> {reservation.start_date} to {reservation.end_date}",
            body,
        )
    )
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("<b>Parties</b>", styles["Heading2"]))
    story.append(
        Paragraph(
            f"<b>Renter (tenant):</b> {_full_name(renter)} &lt;{renter.email}&gt;",
            body,
        )
    )
    story.append(
        Paragraph(
            f"<b>Landlord:</b> {_full_name(lister)} &lt;{lister.email}&gt;",
            body,
        )
    )
    story.append(Spacer(1, 0.5 * cm))
    story.append(
        Paragraph(
            "Signatures are recorded on the following pages when each party confirms in the app.",
            body,
        )
    )
    doc.build(story)
    return buf.getvalue()


def build_signature_page_bytes(
    *,
    role: str,
    full_name: str,
    email: str,
    signed_at,
    signature_png_bytes: bytes | None = None,
) -> bytes:
    """One-page certificate appended after each signature (test harness)."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()
    body = ParagraphStyle(
        name="SigBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
    )
    when = timezone.localtime(signed_at).strftime("%Y-%m-%d %H:%M %Z")
    story = [
        Paragraph("Electronic signature certificate (test)", styles["Heading2"]),
        Spacer(1, 0.4 * cm),
        Paragraph(
            f"<b>Role:</b> {role}<br/>"
            f"<b>Name:</b> {full_name}<br/>"
            f"<b>Email:</b> {email}<br/>"
            f"<b>Signed at:</b> {when}<br/><br/>"
            "The image below is the signature captured when this party signed in Yallastay. "
            "Replace with a certified e-sign provider for production.",
            body,
        ),
    ]
    if signature_png_bytes:
        try:
            pil_buf = io.BytesIO(signature_png_bytes)
            pil = PILImage.open(pil_buf)
            pil.load()
            w_px, h_px = pil.size
            pil_buf.seek(0)
            max_w = 8 * cm
            target_h = max_w * (h_px / w_px) if w_px else 2 * cm
            story.append(Spacer(1, 0.25 * cm))
            story.append(
                Paragraph("<b>Signature:</b>", body),
            )
            story.append(Spacer(1, 0.15 * cm))
            story.append(RLImage(pil_buf, width=max_w, height=target_h))
        except Exception:
            logger.exception("esign.signature_page.embed_image_failed")
            story.append(
                Paragraph(
                    "<i>(Signature image could not be embedded.)</i>",
                    body,
                )
            )
    else:
        story.append(Spacer(1, 0.3 * cm))
        story.append(
            Paragraph(
                "<i>No signature image on file (legacy session).</i>",
                body,
            ),
        )
    doc.build(story)
    return buf.getvalue()


def overlay_png_on_pdf_page(
    pdf_bytes: bytes,
    page_index: int,
    png_bytes: bytes,
    x: float,
    y: float,
    width: float,
    height: float,
) -> bytes:
    """
    Draw PNG on a single page at (x, y) with given size.
    Coordinates: PDF user space, origin bottom-left, points (1/72 inch).
    """
    reader = PdfReader(io.BytesIO(pdf_bytes))
    writer = PdfWriter()
    for i, page in enumerate(reader.pages):
        if i != page_index:
            writer.add_page(page)
            continue
        mb = page.mediabox
        pw = float(mb.width)
        ph = float(mb.height)
        packet = io.BytesIO()
        can = canvas.Canvas(packet, pagesize=(pw, ph))
        try:
            can.drawImage(
                ImageReader(io.BytesIO(png_bytes)),
                x,
                y,
                width=width,
                height=height,
                mask="auto",
            )
        except Exception:
            logger.exception("esign.overlay.draw_image_failed page=%s", page_index)
        can.save()
        packet.seek(0)
        overlay_pdf = PdfReader(packet)
        overlay_page = overlay_pdf.pages[0]
        page.merge_page(overlay_page)
        writer.add_page(page)
    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()


def merge_pdf_parts(parts: list[bytes]) -> bytes:
    writer = PdfWriter()
    for raw in parts:
        reader = PdfReader(io.BytesIO(raw))
        for page in reader.pages:
            writer.add_page(page)
    out = io.BytesIO()
    writer.write(out)
    return out.getvalue()


def attach_contract_pdf_to_session(session: LeaseSigningSession) -> None:
    """Generate baseline PDF and save on session (call right after session create)."""
    from bookings.models import Reservation
    from esign.models import LeaseSigningSession

    if not isinstance(session, LeaseSigningSession):
        return
    reservation = Reservation.objects.select_related(
        "user",
        "listing",
        "listing__listed_by",
        "listing__property_owner",
    ).get(pk=session.reservation_id)
    try:
        raw = build_contract_pdf_bytes(reservation)
    except Exception:
        logger.exception("esign.contract_pdf.generate_failed session_id=%s", session.pk)
        return
    digest = sha256_hex(raw)
    fname = f"lease-session-{session.pk}-contract.pdf"
    session.contract_pdf.save(fname, ContentFile(raw), save=False)
    session.contract_pdf_sha256 = digest
    meta = dict(session.provider_metadata or {})
    meta.setdefault("pdf_mode", "local_reportlab")
    meta["pdf_version"] = 1
    session.provider_metadata = meta
    session.save(
        update_fields=[
            "contract_pdf",
            "contract_pdf_sha256",
            "provider_metadata",
            "updated_at",
        ]
    )
    logger.info(
        "esign.contract_pdf.attached session_id=%s sha256=%s...",
        session.pk,
        digest[:12],
    )


def _read_renter_overlay_png(
    session: LeaseSigningSession, slot_index: int, n_rects: int
) -> bytes | None:
    """One PNG per placement when n_rects > 1; else legacy single file."""
    if n_rects > 1:
        f = getattr(session, f"renter_signature_slot_{slot_index + 1}", None)
        if f and getattr(f, "name", None):
            try:
                with f.open("rb") as fh:
                    return fh.read()
            except Exception:
                logger.exception(
                    "esign.read_renter_slot session_id=%s slot=%s",
                    session.pk,
                    slot_index,
                )
        return None
    if session.renter_signature_image:
        try:
            with session.renter_signature_image.open("rb") as fh:
                return fh.read()
        except Exception:
            logger.exception("esign.read_renter_signature session_id=%s", session.pk)
    return None


def _read_lister_overlay_png(
    session: LeaseSigningSession, slot_index: int, n_rects: int
) -> bytes | None:
    if n_rects > 1:
        f = getattr(session, f"lister_signature_slot_{slot_index + 1}", None)
        if f and getattr(f, "name", None):
            try:
                with f.open("rb") as fh:
                    return fh.read()
            except Exception:
                logger.exception(
                    "esign.read_lister_slot session_id=%s slot=%s",
                    session.pk,
                    slot_index,
                )
        return None
    if session.lister_signature_image:
        try:
            with session.lister_signature_image.open("rb") as fh:
                return fh.read()
        except Exception:
            logger.exception("esign.read_lister_signature session_id=%s", session.pk)
    return None


def contract_base_bytes(session: LeaseSigningSession) -> bytes | None:
    """Prefer lister upload over auto-generated contract PDF."""
    f = session.lister_contract_pdf or session.contract_pdf
    if not f:
        return None
    with f.open("rb") as fh:
        return fh.read()


def rebuild_signed_pdf(session: LeaseSigningSession) -> None:
    """Rebuild signed_pdf from contract + certificate pages for each completed signature."""
    from esign.models import LeaseSigningSession

    session = LeaseSigningSession.objects.select_related(
        "reservation",
        "reservation__user",
        "reservation__listing",
        "reservation__listing__listed_by",
        "reservation__listing__property_owner",
    ).get(pk=session.pk)

    contract_bytes = contract_base_bytes(session)
    if not contract_bytes:
        return

    boxes = normalize_signature_field_boxes(session.signature_field_boxes)
    if boxes:
        pdf_out = contract_bytes
        if session.renter_signed_at:
            renter_rects = boxes["renter"]
            if isinstance(renter_rects, dict):
                renter_rects = [renter_rects]
            for i, br in enumerate(renter_rects):
                renter_sig = _read_renter_overlay_png(session, i, len(renter_rects))
                if renter_sig:
                    pdf_out = overlay_png_on_pdf_page(
                        pdf_out,
                        int(br["page_index"]),
                        renter_sig,
                        float(br["x"]),
                        float(br["y"]),
                        float(br["width"]),
                        float(br["height"]),
                    )
        if session.lister_signed_at:
            lister_rects = boxes["lister"]
            if isinstance(lister_rects, dict):
                lister_rects = [lister_rects]
            for i, bl in enumerate(lister_rects):
                lister_sig = _read_lister_overlay_png(session, i, len(lister_rects))
                if lister_sig:
                    pdf_out = overlay_png_on_pdf_page(
                        pdf_out,
                        int(bl["page_index"]),
                        lister_sig,
                        float(bl["x"]),
                        float(bl["y"]),
                        float(bl["width"]),
                        float(bl["height"]),
                    )

        if not session.renter_signed_at and not session.lister_signed_at:
            if session.signed_pdf:
                session.signed_pdf.delete(save=False)
            session.signed_pdf = None
            session.save(update_fields=["signed_pdf", "updated_at"])
            return

        try:
            fname = f"lease-session-{session.pk}-signed.pdf"
            if session.signed_pdf:
                session.signed_pdf.delete(save=False)
            session.signed_pdf.save(fname, ContentFile(pdf_out), save=False)
            session.save(update_fields=["signed_pdf", "updated_at"])
            logger.info(
                "esign.signed_pdf.rebuilt_overlay session_id=%s mode=field_boxes",
                session.pk,
            )
        except Exception:
            logger.exception(
                "esign.signed_pdf.overlay_save_failed session_id=%s", session.pk
            )
        return

    parts: list[bytes] = [contract_bytes]
    reservation = session.reservation
    renter = reservation.user
    lister = lease_signing_lister_user(reservation.listing)

    if session.renter_signed_at:
        renter_sig: bytes | None = None
        if session.renter_signature_image:
            try:
                with session.renter_signature_image.open("rb") as fh:
                    renter_sig = fh.read()
            except Exception:
                logger.exception(
                    "esign.read_renter_signature session_id=%s", session.pk
                )
        parts.append(
            build_signature_page_bytes(
                role="Renter (tenant)",
                full_name=_full_name(renter),
                email=renter.email,
                signed_at=session.renter_signed_at,
                signature_png_bytes=renter_sig,
            )
        )
    if session.lister_signed_at:
        lister_sig: bytes | None = None
        if session.lister_signature_image:
            try:
                with session.lister_signature_image.open("rb") as fh:
                    lister_sig = fh.read()
            except Exception:
                logger.exception(
                    "esign.read_lister_signature session_id=%s", session.pk
                )
        parts.append(
            build_signature_page_bytes(
                role="Landlord",
                full_name=_full_name(lister),
                email=lister.email,
                signed_at=session.lister_signed_at,
                signature_png_bytes=lister_sig,
            )
        )

    if len(parts) == 1:
        if session.signed_pdf:
            session.signed_pdf.delete(save=False)
        session.signed_pdf = None
        session.save(update_fields=["signed_pdf", "updated_at"])
        return

    try:
        merged = merge_pdf_parts(parts)
    except Exception:
        logger.exception("esign.signed_pdf.merge_failed session_id=%s", session.pk)
        return

    fname = f"lease-session-{session.pk}-signed.pdf"
    if session.signed_pdf:
        session.signed_pdf.delete(save=False)
    session.signed_pdf.save(fname, ContentFile(merged), save=False)
    session.save(update_fields=["signed_pdf", "updated_at"])
    logger.info(
        "esign.signed_pdf.rebuilt session_id=%s pages=%s", session.pk, len(parts)
    )
