# Generated by Django 6.0.2 on 2026-06-19 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_partnership_chat_attachments"),
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("inquiry", "Renter inquiry"),
                    ("partnership", "Owner and broker"),
                ],
                db_index=True,
                default="inquiry",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="messaging/attachments/"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachment_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "partnership")),
                fields=("listing", "kind"),
                name="messaging_unique_partnership_per_listing",
            ),
        ),
    ]
