# Generated by Django 6.0.2 on 2026-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_realtorprofile_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtorprofile",
            name="orn",
            field=models.CharField(
                blank=True,
                help_text="Office Registration Number (RERA), if applicable.",
                max_length=64,
            ),
        ),
    ]
