# Generated by Django 6.0.2 on 2026-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_userprofile_renter_search_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordprofile",
            name="is_emirati",
            field=models.BooleanField(
                blank=True,
                help_text="If False, a residence visa is required for verification (in addition to passport).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="realtorprofile",
            name="brokerage_type",
            field=models.CharField(
                choices=[
                    ("private", "Private broker"),
                    ("agency", "Agency / brokerage"),
                ],
                default="agency",
                help_text="Private brokers are shown first to owners (less paperwork) when selecting a realtor.",
                max_length=20,
            ),
        ),
    ]
