# Generated by Django 6.0.2 on 2026-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_uae_verification_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_lifestyle",
            field=models.BooleanField(
                default=False,
                help_text="If true, user can access the lifestyle team dashboard (Services page) without Django staff.",
            ),
        ),
    ]
