# Generated by Django 6.0.2 on 2026-05-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_userprofile_can_manage_lifestyle"),
    ]

    operations = [
        migrations.AddField(
            model_name="landlordprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="landlordprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
