# Generated by Django 6.0.2 on 2026-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("uae_id", "UAE ID"),
                    ("university", "University Verification"),
                    ("lease_agreement", "Lease Agreement"),
                    ("realtor_license", "Realtor / brokerage license"),
                    ("trade_license", "Trade license (DET / Free Zone)"),
                    ("rera_broker_card", "RERA Broker Card (BRN)"),
                    ("orn", "ORN certificate / document"),
                    ("noc_agency", "NOC (sponsoring agency)"),
                    ("passport", "Passport"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
