# Generated by Django 6.0.2 on 2026-04-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_uae_verification_pipeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("uae_id", "UAE ID (supporting scan / copy)"),
                    ("university", "University Verification"),
                    ("lease_agreement", "Lease Agreement"),
                    ("realtor_license", "Realtor / brokerage license"),
                    ("trade_license", "Trade licence (DET / Free Zone)"),
                    ("rera_broker_card", "RERA Broker Card (BRN)"),
                    ("orn", "ORN (Office Registration Number) certificate"),
                    ("agency_supplementary_licence", "Agency / supplementary licence"),
                    ("noc_agency", "NOC (sponsoring agency)"),
                    ("passport", "Passport"),
                    ("residence_visa", "Residence visa"),
                    ("title_deed", "Title deed (property ownership, PDF only)"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
