# Generated by Django 6.0.2 on 2026-03-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("viewing", "Viewing"),
                    ("message", "Message"),
                    ("payment", "Payment"),
                    ("lifestyle", "Lifestyle"),
                    ("review", "Review"),
                    ("listing", "Listing"),
                    ("general", "General"),
                ],
                max_length=20,
            ),
        ),
    ]
