# Generated by Django 6.0.2 on 2026-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_link_and_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("viewing", "Viewing"),
                    ("message", "Message"),
                    ("payment", "Payment"),
                    ("lifestyle", "Lifestyle"),
                    ("review", "Review"),
                    ("listing", "Listing"),
                    ("general", "General"),
                    ("welcome", "Welcome"),
                    ("email_verified", "Email verified"),
                    ("documents_verified", "Documents verified"),
                    ("uae_verified", "UAE ID verified"),
                    ("acceptance", "Acceptance"),
                    ("contract", "Contract"),
                    ("esign", "E-sign / lease"),
                ],
                max_length=30,
            ),
        ),
    ]
