# Generated by Django 6.0.2 on 2026-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_reservation_notes_dld_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="keys_received_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the renter confirmed they collected keys (in-app handover checkpoint).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="platform_feedback",
            field=models.TextField(
                blank=True,
                help_text="Optional private feedback from the renter about the platform (not a public review).",
            ),
        ),
    ]
